mod 'boxen',  '1.2.0',  :github_tarball => 'boxen/puppet-boxen'
mod 'osx',    '1.0.0',  :github_tarball => 'boxen/puppet-osx'
mod 'stdlib', '3.0.0',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
